show:
	cp slides.html /cs/home/hxiao/public_html/
	cp *.png /cs/home/hxiao/public_html/shared_images
	chmod a+r /cs/home/hxiao/public_html/shared_images/*.png
	chmod a+r /cs/home/hxiao/public_html/slides.html
